### ISSUE TITLE
FulfillmentLocationsList can not read property of null

### ISSUE THREAD

**Issue by evrastil** [Cimpress/react-cimpress-fulfillers-components#14]
When typing fast or using special characters ie: "[]" `FulfillmentLocationsList`
 component fails with error `can not read read property length of null`. The issue seems to be that `filteredLocations` and `filteredRecentLocations` is null sometimes. Easy fix is to check for those nulls. I have created PR but may be here is better way how to fix this.

The issue can be reproduced in demo https://trdlnk.cimpress.io/demo-fulfillers-components
 
PR is here https://github.com/Cimpress/react-cimpress-fulfillers-components/pull/13

**Comment by istanishev** [comment]
Addressed.
